module.exports = [
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 1",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹11000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 2",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹12000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 3",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹13000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 4",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹14000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 5",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹15000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 6",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹16000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 7",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹17000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 8",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹18000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 9",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹19000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 10",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹20000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 11",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹21000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 12",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹22000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 13",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹23000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 14",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹24000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 15",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹25000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 16",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹26000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 17",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹27000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 18",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹28000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 19",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹29000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 20",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹30000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 21",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹31000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 22",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹32000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 23",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹33000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 24",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹34000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 25",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹35000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 26",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹36000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 27",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹37000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 28",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹38000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 29",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹39000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 30",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹40000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 31",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹41000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 32",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹42000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 33",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹43000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 34",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹44000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 35",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹45000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 36",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹46000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 37",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹47000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 38",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹48000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 39",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹49000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 40",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹50000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 41",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹51000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 42",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹52000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  },
  {
    "title": "Merit-cum-Means Scholarship for B.Tech Students 43",
    "description": "Financial assistance for meritorious students pursuing engineering degrees.",
    "level": "UG",
    "branch": "Engineering",
    "amount": "₹53000",
    "deadline": "2024-12-31",
    "link": "https://scholarships.gov.in",
    "verified": true,
    "provider": "Govt of India"
  }
];